### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by rfv406406**
智偉  

http://52.200.212.151:3000/

http://52.200.212.151:3000/attraction/1

### CODE REVIEW

**Comment by cwpeng** [comment]
You have to request review so that I can review for you.

**Comment by rfv406406** [comment]
OK. Done. Thank you!

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. There is no space between navigator bar and image slider in mobile layout.
2. There should have more spacing between second separating line and attraction description text.

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Comment by cwpeng** [comment]
You should merge pull request after review approval. If you cannot understand what is difference between merging and closing, try to find it out and do in the right way.

**Pull request closed without merging**
