### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by rfv406406**
老師您好~  我是智偉!

作業請您校閱，感謝!

### CODE REVIEW

**Comment by rfv406406** [comment]
http://52.200.212.151:3000/  補上網址><

**Review by cwpeng — CHANGES_REQUESTED** [review]
Don't show alert dialog showing prime key.

**Comment by rfv406406** [comment]
1.Canceled showing primekey in alert.

Thank you teacher!

**Review by cwpeng — CHANGES_REQUESTED** [review]
Don't show get prime successfully dialog for end users. You should think from user's view, for example, can your parents understand what your dialog says? can they understand what is prime? In your experience on e-commerce website, any website will show message for you like this?

**Comment by rfv406406** [comment]
OK!  I can totally understand it. It's truly I didn't consider the opinion from user.
The alerts about getting prime was commented out.

Thanks!!

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
